#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# MIT / BSD / ISC / Apache-2.0 all require the copyright notice and the licence
# text to travel with every copy of the software. lilmail ships Go dependencies
# compiled into its binary and vendored JavaScript served to the browser, so the
# notices must ship with it. This script rebuilds the notices file; it is NOT
# hand-maintained. Run it whenever go.mod or assets/vendor/ changes:
#
#     ./scripts/gen-notices.sh
#
# The generated file is committed (go:embed needs it at build time) and served
# to users at /licenses.txt.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# go-licence-detector (Elastic) walks the real module graph and reproduces the
# full licence text of every module from the module cache.
DETECTOR="$(command -v go-licence-detector || true)"
if [[ -z "$DETECTOR" ]]; then
  echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
  GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0
  DETECTOR="$TMP/bin/go-licence-detector"
fi

echo "==> resolving Go module graph"
go mod download
go list -m -json all | "$DETECTOR" \
  -includeIndirect \
  -noticeTemplate scripts/notices/go-modules.tmpl \
  -noticeOut "$TMP/go-notices.txt"

echo "==> composing $OUT"
{
  cat <<'HEADER'
================================================================================
lilmail — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

lilmail is distributed under the MIT licence (see LICENSE). It bundles the
third-party software listed below. Each entry gives the component name, its
version, the licence it is distributed under, and the full text of that licence,
as those licences require. lilmail serves this file at /licenses.txt.

HEADER

  echo "================================================================================"
  echo "Vendored browser assets (served from /assets/vendor/)"
  echo "================================================================================"
  echo
  for lic in assets/vendor/*.LICENSE; do
    [[ -e "$lic" ]] || continue
    echo "--------------------------------------------------------------------------------"
    cat "$lic"
    echo
  done

  echo "================================================================================"
  echo "Go standard library (compiled into the lilmail binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  cat "$(go env GOROOT)/LICENSE"
  echo
  cat "$(go env GOROOT)/PATENTS"
  echo

  echo "================================================================================"
  echo "Go modules (compiled into the lilmail binary)"
  echo "================================================================================"
  echo
  cat "$TMP/go-notices.txt"
} > "$OUT"

echo "==> wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
